/**
 * Generates the SQL migration that expands `public.ports` from the original
 * 53-port hand-seed to global coverage, using the NGA World Port Index
 * snapshot in `scripts/port-data/` (see that directory's README for source
 * and licensing).
 *
 * This script only ever WRITES a `.sql` file under `supabase/migrations/` —
 * it never touches a database. Run it, review the generated file, then apply
 * it through the normal Supabase migration flow like any other migration.
 *
 *   npx tsx scripts/generate-ports-migration.ts
 *
 * Re-running it regenerates the same migration deterministically from the
 * same input snapshot (useful if the derivation rules below change), but it
 * does not overwrite a previously generated file — it always writes a fresh
 * timestamped one, since migrations already applied must never be edited.
 *
 * --- Filtering & derivation rules -----------------------------------------
 *
 * Source rows: every WPI row that has a name and coordinates (all 3,807 —
 * the source has none missing either). No further "is this significant
 * enough" filter is applied on top of WPI's own curation: WPI is already a
 * human-vetted catalog of ports NGA considers navigationally significant,
 * not a crowd-sourced list of every dock, so it inherently excludes
 * marinas, recreational boating locations, airports, and administrative
 * locations without needing a second filter pass.
 *
 * UN/LOCODE: taken directly from WPI's own `UN/LOCODE` column (present on
 * ~88% of rows) rather than cross-referenced against a separate UN/LOCODE
 * dataset. A value is only accepted if it has the exact shape of a real
 * code (5 letters/digits, or 6 with a single space at position 2) — a
 * handful of corrupted values in the source (stray quotes, truncated
 * codes) are rejected rather than guessed into a plausible-looking code.
 * Where two WPI rows legitimately share one UN/LOCODE (this happens: e.g.
 * "Dunkerque Port Ouest" and "Dunkerque Port Est" both carry FRDKK), the
 * larger-harbor-size row keeps the code and the other is still imported as
 * its own port, with no UN/LOCODE — never two ports rows fabricating the
 * same code, and never a real distinct terminal silently dropped.
 *
 * geofence_radius_km: derived from WPI's `Harbor Size` classification
 * (Very Small/Small/Medium/Large) rather than one flat number, so a
 * compact harbor and a sprawling port complex get meaningfully different
 * defaults. Still fully editable per-row afterward — this only sets the
 * initial value.
 *
 * port_type: derived from WPI's `Harbor Use` and per-facility flags
 * (container/solid-bulk/liquid-bulk/oil-terminal/LNG-terminal/breakbulk),
 * in priority order — see `derivePortType()`. Never guessed beyond what
 * the source data actually states; falls back to 'general'.
 *
 * --- Merge with the existing 53 ports --------------------------------------
 *
 * Ports are matched to the live table by UN/LOCODE alone (a stable natural
 * key), never by name (spelling varies too much across sources to match
 * safely) and never by id (the original seed migration never hardcoded
 * ids — they were generated by the database). For each WPI row with a
 * valid code:
 *
 *   UPDATE public.ports SET latitude=…, longitude=…, port_type=…,
 *     geofence_radius_km=…, source='nga_wpi', source_identifier=…,
 *     active=true, updated_at=now()
 *   WHERE unlocode = '<code>' AND source_identifier IS NULL;
 *
 *   INSERT INTO public.ports (…) SELECT … WHERE NOT EXISTS
 *     (SELECT 1 FROM public.ports WHERE unlocode = '<code>');
 *
 * The UPDATE is a no-op if no port has that code yet (nothing to improve);
 * the INSERT only fires if no port has that code at all. Together they
 * mean: an existing port with a matching code gets its id preserved and its
 * data upgraded in place (so every shipment's origin_port_id /
 * destination_port_id keeps pointing at the same row); a code with no
 * existing match becomes a new port; and the whole migration is safe to
 * apply twice (the `source_identifier IS NULL` guard makes the UPDATE a
 * no-op on a second run, and the INSERT's NOT EXISTS guard does the same).
 *
 * A handful of the original 53 (Shanghai, Ningbo-Zhoushan, Shenzhen,
 * Guangzhou, Qingdao, Singapore) use UN/LOCODEs that WPI does not carry
 * under an exact-matching code — WPI represents some of these as several
 * separate terminal entries instead (e.g. Singapore as Jurong Island,
 * Keppel, Pulau Bukom, Pulau Sebarok, Serangoon Harbor). Rather than
 * fuzzy-match names across datasets (real risk of matching the wrong
 * place), these six keep their existing hand-set coordinates untouched,
 * and WPI's own entries for those terminals are imported alongside them as
 * additional, separately-selectable ports — which is also a more accurate
 * reflection of reality for a port complex with multiple distinct
 * terminals.
 *
 * Rows with no usable UN/LOCODE are inserted keyed on
 * (source, source_identifier) = ('nga_wpi', <WPI number>) instead, the
 * same idempotency guarantee via a different natural key.
 */
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

type WpiRow = {
  oid: string;
  wpi: string;
  name: string;
  unlocode: string;
  country: string;
  size: string;
  type: string;
  use: string;
  container: string;
  solidBulk: string;
  liquidBulk: string;
  oilTerminal: string;
  lngTerminal: string;
  breakbulk: string;
  lat: number;
  lon: number;
};

const HARBOR_SIZE_RADIUS_KM: Record<string, number> = {
  Large: 28,
  Medium: 20,
  Small: 14,
  "Very Small": 9,
};
const DEFAULT_RADIUS_KM = 14;

function deriveRadiusKm(size: string): number {
  return HARBOR_SIZE_RADIUS_KM[size] ?? DEFAULT_RADIUS_KM;
}

function derivePortType(row: WpiRow): string {
  if (row.container === "Yes") return "container";
  if (row.use === "Fishing") return "fishing";
  if (row.use === "Ferry") return "ferry";
  if (row.use === "Military") return "military";
  if (row.oilTerminal === "Yes" || row.lngTerminal === "Yes") return "terminal";
  if (row.use === "Cargo" || row.solidBulk === "Yes" || row.liquidBulk === "Yes" || row.breakbulk === "Yes") {
    return "cargo";
  }
  return "general";
}

const HARBOR_SIZE_RANK: Record<string, number> = { Large: 4, Medium: 3, Small: 2, "Very Small": 1, "": 0 };

/** Accepts "USANC" (5 chars) or "US ANC" (6 chars, space at index 2) only —
 * anything else in the source (stray quotes, truncated fragments, bare
 * 2-letter country codes) is rejected rather than guessed into shape. */
function normalizeUnlocode(raw: string): string | null {
  const trimmed = raw.trim().toUpperCase();
  if (/^[A-Z]{2}[A-Z0-9]{3}$/.test(trimmed)) return trimmed;
  if (trimmed.length === 6 && trimmed[2] === " " && /^[A-Z]{2} [A-Z0-9]{3}$/.test(trimmed)) {
    return trimmed.slice(0, 2) + trimmed.slice(3);
  }
  return null;
}

function sqlString(value: string | null): string {
  if (value == null) return "NULL";
  return `'${value.replace(/'/g, "''")}'`;
}

function main() {
  const dataPath = join(import.meta.dirname, "port-data", "nga-world-port-index.json");
  const rows = (JSON.parse(readFileSync(dataPath, "utf-8")) as WpiRow[]).map((row) => ({
    ...row,
    // The source CSV renders these as e.g. "19800.0" — strip the trailing
    // ".0". `oid` (not `wpi`) is used as source_identifier below: the
    // "World Port Index Number" itself has two real duplicate pairs in the
    // source data (e.g. Escravos Oil Terminal and Lekki, two distinct
    // Nigerian ports, both carry WPI number 46135) — caught by testing this
    // migration against a real Postgres instance before it ever reached
    // the actual database. `OID_`, the source's own row-export id, has no
    // duplicates and is the reliable per-row key.
    oid: row.oid.replace(/\.0$/, ""),
    wpi: row.wpi.replace(/\.0$/, ""),
  }));

  // Resolve WPI-internal UN/LOCODE collisions: keep the larger-harbor-size
  // row's claim to the code; every row is still imported either way.
  const codeOwner = new Map<string, WpiRow>();
  for (const row of rows) {
    const code = normalizeUnlocode(row.unlocode);
    if (!code) continue;
    const current = codeOwner.get(code);
    if (!current || HARBOR_SIZE_RANK[row.size]! > HARBOR_SIZE_RANK[current.size]!) {
      codeOwner.set(code, row);
    }
  }

  const lines: string[] = [];
  let insertCount = 0;
  let updateCount = 0;

  for (const row of rows) {
    const rawCode = normalizeUnlocode(row.unlocode);
    const code = rawCode && codeOwner.get(rawCode) === row ? rawCode : null;
    const radius = deriveRadiusKm(row.size);
    const portType = derivePortType(row);
    const name = row.name;
    const country = row.country || null;

    if (code) {
      updateCount++;
      lines.push(
        `UPDATE public.ports SET latitude = ${row.lat}, longitude = ${row.lon}, port_type = ${sqlString(portType)}, geofence_radius_km = ${radius}, source = 'nga_wpi', source_identifier = ${sqlString(row.oid)}, active = true, updated_at = now() WHERE unlocode = ${sqlString(code)} AND source_identifier IS NULL;`,
      );
      insertCount++;
      lines.push(
        `INSERT INTO public.ports (name, unlocode, country, latitude, longitude, geofence_radius_km, port_type, source, source_identifier, active) SELECT ${sqlString(name)}, ${sqlString(code)}, ${sqlString(country)}, ${row.lat}, ${row.lon}, ${radius}, ${sqlString(portType)}, 'nga_wpi', ${sqlString(row.oid)}, true WHERE NOT EXISTS (SELECT 1 FROM public.ports WHERE unlocode = ${sqlString(code)});`,
      );
    } else {
      insertCount++;
      lines.push(
        `INSERT INTO public.ports (name, unlocode, country, latitude, longitude, geofence_radius_km, port_type, source, source_identifier, active) SELECT ${sqlString(name)}, NULL, ${sqlString(country)}, ${row.lat}, ${row.lon}, ${radius}, ${sqlString(portType)}, 'nga_wpi', ${sqlString(row.oid)}, true WHERE NOT EXISTS (SELECT 1 FROM public.ports WHERE source = 'nga_wpi' AND source_identifier = ${sqlString(row.oid)});`,
      );
    }
  }

  const timestamp = "20260921000000";
  const outPath = join(
    import.meta.dirname,
    "..",
    "supabase",
    "migrations",
    `${timestamp}_expand_global_port_coverage.sql`,
  );

  const sql = `-- Expands the port reference database from the original 53-port hand
-- seed to global coverage, using the NGA World Port Index (public domain,
-- US government work — see scripts/port-data/README.md for full source and
-- licensing notes). Generated by scripts/generate-ports-migration.ts —
-- regenerate that script's output rather than hand-editing this file.
--
-- ${rows.length} source ports processed: ${updateCount} matched an existing
-- UN/LOCODE and upgrade that port's data in place (id preserved, so every
-- shipment's origin_port_id/destination_port_id keeps resolving correctly);
-- the rest are new ports. Idempotent — safe to apply more than once.

-- New columns on the existing table. Defaults backfill every current row
-- (the original 53) as 'general'/'manual_seed'/active — the statement right
-- after this block upgrades them to 'container', matching that seed's own
-- documented intent ("major ocean container/trade ports"); the per-port
-- UPDATEs below further refine anything WPI has better data for.
ALTER TABLE public.ports
  ADD COLUMN IF NOT EXISTS port_type text NOT NULL DEFAULT 'general',
  ADD COLUMN IF NOT EXISTS source text NOT NULL DEFAULT 'manual_seed',
  ADD COLUMN IF NOT EXISTS source_identifier text,
  ADD COLUMN IF NOT EXISTS active boolean NOT NULL DEFAULT true,
  ADD COLUMN IF NOT EXISTS updated_at timestamptz NOT NULL DEFAULT now();

UPDATE public.ports SET port_type = 'container' WHERE source = 'manual_seed';

-- Idempotency key for the WPI import, independent of unlocode (~12% of WPI
-- rows have none) and independent of id (never hardcoded by the original
-- seed, so it isn't known here).
CREATE UNIQUE INDEX IF NOT EXISTS ports_source_identifier_idx
  ON public.ports (source, source_identifier) WHERE source_identifier IS NOT NULL;

DROP TRIGGER IF EXISTS ports_touch_updated_at ON public.ports;
CREATE TRIGGER ports_touch_updated_at BEFORE UPDATE ON public.ports
  FOR EACH ROW EXECUTE FUNCTION public.touch_updated_at();

-- Fast substring search over a few thousand rows (and comfortably further —
-- trigram + GIN scales well past this dataset's size) for the port picker's
-- server-side search, plus a plain index for the country filter and a
-- partial index over the common "active only" read path.
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS ports_name_trgm_idx ON public.ports USING gin (name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS ports_country_idx ON public.ports (country);
CREATE INDEX IF NOT EXISTS ports_active_idx ON public.ports (active) WHERE active;

-- ${rows.length} ports from the NGA World Port Index: ${updateCount} upgrade an
-- existing port in place, ${rows.length - updateCount} are new.
${lines.join("\n")}

-- Link the existing AIS test shipment(s) to their newly-available structured
-- ports, wherever the free-text origin/destination already names them and no
-- structured link exists yet. Additive only — never overwrites an existing
-- origin_port_id/destination_port_id, and never touches the free-text
-- columns themselves.
UPDATE public.shipments s SET destination_port_id = p.id
  FROM public.ports p
  WHERE s.destination_port_id IS NULL AND p.unlocode = 'USANC' AND s.destination ILIKE '%anchorage%';

UPDATE public.shipments s SET origin_port_id = p.id
  FROM public.ports p
  WHERE s.origin_port_id IS NULL AND p.unlocode = 'USTIW' AND s.origin ILIKE '%tacoma%';
`;

  writeFileSync(outPath, sql, "utf-8");
  console.log(`Wrote ${outPath}`);
  console.log(`${rows.length} source rows -> ${updateCount} updates, ${insertCount} inserts`);
}

main();
