/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AlertsRouteImport } from './routes/alerts'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as DocumentsRouteImport } from './routes/documents'
import { Route as MapRouteImport } from './routes/map'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as VesselsRouteImport } from './routes/vessels'
import { Route as ShipmentsIndexRouteImport } from './routes/shipments.index'
import { Route as ShipmentsIdRouteImport } from './routes/shipments.$id'
import { Route as ShipmentsActiveRouteImport } from './routes/shipments.active'
import { Route as ShipmentsCompletedRouteImport } from './routes/shipments.completed'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AlertsRoute = AlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentsRoute = DocumentsRouteImport.update({
  id: '/documents',
  path: '/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const MapRoute = MapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VesselsRoute = VesselsRouteImport.update({
  id: '/vessels',
  path: '/vessels',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIndexRoute = ShipmentsIndexRouteImport.update({
  id: '/shipments/',
  path: '/shipments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsIdRoute = ShipmentsIdRouteImport.update({
  id: '/shipments/$id',
  path: '/shipments/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsActiveRoute = ShipmentsActiveRouteImport.update({
  id: '/shipments/active',
  path: '/shipments/active',
  getParentRoute: () => rootRouteImport,
} as any)
const ShipmentsCompletedRoute = ShipmentsCompletedRouteImport.update({
  id: '/shipments/completed',
  path: '/shipments/completed',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/documents': typeof DocumentsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/vessels': typeof VesselsRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/active': typeof ShipmentsActiveRoute
  '/shipments/completed': typeof ShipmentsCompletedRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/documents': typeof DocumentsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/vessels': typeof VesselsRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/active': typeof ShipmentsActiveRoute
  '/shipments/completed': typeof ShipmentsCompletedRoute
  '/shipments': typeof ShipmentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/alerts': typeof AlertsRoute
  '/analytics': typeof AnalyticsRoute
  '/documents': typeof DocumentsRoute
  '/map': typeof MapRoute
  '/settings': typeof SettingsRoute
  '/vessels': typeof VesselsRoute
  '/shipments/$id': typeof ShipmentsIdRoute
  '/shipments/active': typeof ShipmentsActiveRoute
  '/shipments/completed': typeof ShipmentsCompletedRoute
  '/shipments/': typeof ShipmentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/documents'
    | '/map'
    | '/settings'
    | '/vessels'
    | '/shipments/$id'
    | '/shipments/active'
    | '/shipments/completed'
    | '/shipments/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/alerts'
    | '/analytics'
    | '/documents'
    | '/map'
    | '/settings'
    | '/vessels'
    | '/shipments/$id'
    | '/shipments/active'
    | '/shipments/completed'
    | '/shipments'
  id:
    | '__root__'
    | '/'
    | '/alerts'
    | '/analytics'
    | '/documents'
    | '/map'
    | '/settings'
    | '/vessels'
    | '/shipments/$id'
    | '/shipments/active'
    | '/shipments/completed'
    | '/shipments/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AlertsRoute: typeof AlertsRoute
  AnalyticsRoute: typeof AnalyticsRoute
  DocumentsRoute: typeof DocumentsRoute
  MapRoute: typeof MapRoute
  SettingsRoute: typeof SettingsRoute
  VesselsRoute: typeof VesselsRoute
  ShipmentsIdRoute: typeof ShipmentsIdRoute
  ShipmentsActiveRoute: typeof ShipmentsActiveRoute
  ShipmentsCompletedRoute: typeof ShipmentsCompletedRoute
  ShipmentsIndexRoute: typeof ShipmentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alerts': {
      id: '/alerts'
      path: '/alerts'
      fullPath: '/alerts'
      preLoaderRoute: typeof AlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documents': {
      id: '/documents'
      path: '/documents'
      fullPath: '/documents'
      preLoaderRoute: typeof DocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/map': {
      id: '/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof MapRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vessels': {
      id: '/vessels'
      path: '/vessels'
      fullPath: '/vessels'
      preLoaderRoute: typeof VesselsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/': {
      id: '/shipments/'
      path: '/shipments'
      fullPath: '/shipments/'
      preLoaderRoute: typeof ShipmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/$id': {
      id: '/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof ShipmentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/active': {
      id: '/shipments/active'
      path: '/shipments/active'
      fullPath: '/shipments/active'
      preLoaderRoute: typeof ShipmentsActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipments/completed': {
      id: '/shipments/completed'
      path: '/shipments/completed'
      fullPath: '/shipments/completed'
      preLoaderRoute: typeof ShipmentsCompletedRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AlertsRoute: AlertsRoute,
  AnalyticsRoute: AnalyticsRoute,
  DocumentsRoute: DocumentsRoute,
  MapRoute: MapRoute,
  SettingsRoute: SettingsRoute,
  VesselsRoute: VesselsRoute,
  ShipmentsIdRoute: ShipmentsIdRoute,
  ShipmentsActiveRoute: ShipmentsActiveRoute,
  ShipmentsCompletedRoute: ShipmentsCompletedRoute,
  ShipmentsIndexRoute: ShipmentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
